# Generated by Django 6.0.2 on 2026-03-06 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0003_order_station"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="supplier",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
