# Generated by Django 6.0.2 on 2026-02-20 00:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_order_requested_by_alter_order_approved_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='reason',
        ),
    ]
