# Generated by Django 4.2 on 2026-02-20 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0005_remove_order_reason"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="synced",
            field=models.BooleanField(default=False),
        ),
    ]
