# Generated by Django 4.2 on 2026-02-19 15:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("users", "__first__"),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomerProfile",
            fields=[
                (
                    "profile_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="users.profile",
                    ),
                ),
                ("company_name", models.CharField(blank=True, max_length=255)),
                ("customer_info", models.TextField(blank=True)),
            ],
            bases=("users.profile",),
        ),
    ]
