# Generated by Django 4.2 on 2026-02-20 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customerprofile",
            name="notes",
            field=models.TextField(blank=True),
        ),
    ]
