# Generated by Django 4.2 on 2026-02-20 22:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0002_customerprofile_notes"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customerprofile",
            name="notes",
        ),
    ]
