# Generated by Django 4.2 on 2026-02-21 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0003_remove_customerprofile_notes"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customerprofile",
            name="customer_info",
        ),
    ]
