# Generated by Django 6.0.2 on 2026-03-06 02:05

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("staffs", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="staffprofile",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
    ]
