# Generated by Django 6.0.2 on 2026-03-06 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("staffs", "0003_staffprofile_uuid_pk"),
    ]

    operations = [
        migrations.AlterField(
            model_name="staffprofile",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
