# Generated by Django 4.2 on 2026-02-26 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TechnicianJob",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("severity", models.CharField(default="Medium", max_length=20)),
                ("specialization", models.CharField(default="General", max_length=50)),
                ("expertise", models.CharField(default="Mid", max_length=10)),
                ("date_assigned", models.DateTimeField(auto_now_add=True)),
                ("date_completed", models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="TechnicianProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "specialization",
                    models.CharField(
                        choices=[
                            ("engine", "Engine Technician"),
                            ("electrical", "Electrical Technician"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "expertise",
                    models.CharField(
                        choices=[
                            ("junior", "Junior"),
                            ("mid", "Mid"),
                            ("senior", "Senior"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("available", "Available"),
                            ("busy", "Busy"),
                            ("unavailable", "Unavailable"),
                        ],
                        default="available",
                        max_length=20,
                    ),
                ),
                ("total_years_experience", models.FloatField(default=0.0)),
                ("date_joined", models.DateField(blank=True, null=True)),
                ("performance_rating", models.FloatField(default=0.0)),
                ("total_jobs_completed", models.IntegerField(default=0)),
            ],
        ),
    ]
