# Generated by Django 4.2 on 2026-02-19 15:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("users", "__first__"),
    ]

    operations = [
        migrations.CreateModel(
            name="TechnicianProfile",
            fields=[
                (
                    "profile_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="users.profile",
                    ),
                ),
                (
                    "avatar",
                    models.ImageField(blank=True, null=True, upload_to="avatars/"),
                ),
                (
                    "specialization",
                    models.CharField(
                        choices=[
                            ("engine", "Engine Technician"),
                            ("electrical", "Electrical Technician"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "expertise",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("junior", "Junior"),
                            ("mid", "Mid"),
                            ("senior", "Senior"),
                        ],
                        max_length=10,
                    ),
                ),
                ("is_available", models.BooleanField(default=True)),
                ("latitude", models.FloatField(blank=True, null=True)),
                ("longitude", models.FloatField(blank=True, null=True)),
            ],
            bases=("users.profile",),
        ),
    ]
