# Generated by Django 6.0.2 on 2026-02-26 20:40

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('certification_id', models.CharField(max_length=50, unique=True)),
                ('institution', models.CharField(max_length=100)),
                ('date_obtained', models.DateField()),
                ('expiration_date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TechnicianProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialization', models.CharField(choices=[('engine', 'Engine Technician'), ('electrical', 'Electrical Technician')], max_length=50)),
                ('expertise', models.CharField(choices=[('junior', 'Junior'), ('mid', 'Mid'), ('senior', 'Senior')], max_length=10)),
                ('status', models.CharField(choices=[('available', 'Available'), ('busy', 'Busy'), ('unavailable', 'Unavailable')], default='available', max_length=20)),
                ('total_years_experience', models.FloatField(default=0.0)),
                ('date_joined', models.DateField(blank=True, null=True)),
                ('performance_rating', models.FloatField(default=0.0)),
                ('total_jobs_completed', models.IntegerField(default=0)),
            ],
        ),
    ]
