# Generated by Django 4.2 on 2026-02-26 14:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("users", "0001_initial"),
        ("technicians", "0001_initial"),
        ("tickets", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="technicianprofile",
            name="profile",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="technician_profile",
                to="users.profile",
            ),
        ),
        migrations.AddField(
            model_name="technicianprofile",
            name="station",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="technicians",
                to="users.station",
            ),
        ),
        migrations.AddField(
            model_name="technicianjob",
            name="technician",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="jobs",
                to="technicians.technicianprofile",
            ),
        ),
        migrations.AddField(
            model_name="technicianjob",
            name="ticket",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="technician_jobs",
                to="tickets.ticket",
            ),
        ),
    ]
