# Generated by Django 4.2 on 2026-02-21 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("technicians", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="technicianprofile",
            name="avatar",
        ),
    ]
