# Generated by Django 4.2 on 2026-02-21 07:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0013_station"),
        ("technicians", "0002_remove_technicianprofile_avatar"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="technicianprofile",
            name="latitude",
        ),
        migrations.RemoveField(
            model_name="technicianprofile",
            name="longitude",
        ),
        migrations.AddField(
            model_name="technicianprofile",
            name="location",
            field=models.CharField(blank=True, max_length=240, null=True),
        ),
        migrations.AddField(
            model_name="technicianprofile",
            name="station",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="users.station",
            ),
        ),
    ]
