# Generated by Django 6.0.2 on 2026-02-26 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('technicians', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='technicianprofile',
            name='skill_score',
            field=models.IntegerField(default=1),
        ),
    ]
