# Generated by Django 6.0.2 on 2026-03-05 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("technicians", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="technicianprofile",
            name="hourly_rate",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=0.0, max_digits=10, null=True
            ),
        ),
    ]
