# Generated by Django 4.2 on 2026-02-21 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("technicians", "0003_remove_technicianprofile_latitude_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="technicianprofile",
            name="location",
        ),
    ]
