# Generated by Django 4.2 on 2026-02-21 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("technicians", "0004_remove_technicianprofile_location"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="technicianprofile",
            name="is_available",
        ),
        migrations.AddField(
            model_name="technicianprofile",
            name="status",
            field=models.CharField(
                choices=[
                    ("available", "Available"),
                    ("unavailable", "Unavailable"),
                    ("busy", "Busy"),
                ],
                default="Avaiable",
                max_length=27,
            ),
        ),
    ]
