# Generated by Django 4.2 on 2026-02-22 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("technicians", "0005_remove_technicianprofile_is_available_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="technicianprofile",
            name="expertise",
            field=models.CharField(
                blank=True,
                choices=[("Junior", "Junior"), ("Mid", "Mid"), ("Senior", "Senior")],
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="technicianprofile",
            name="specialization",
            field=models.CharField(
                choices=[
                    ("Engine", "Engine_Technician"),
                    ("Electrical", "Electrical_Technician"),
                ],
                max_length=50,
            ),
        ),
    ]
