# Generated by Django 4.2 on 2026-02-22 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("technicians", "0008_alter_technicianprofile_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="technicianprofile",
            name="status",
            field=models.CharField(
                choices=[
                    ("Busy", "Busy"),
                    ("Unavailable", "Unavailable"),
                    ("Available", "Available"),
                ],
                default="Avaiable",
                max_length=27,
            ),
        ),
    ]
