# Generated by Django 6.0.2 on 2026-02-25 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('technicians', '0019_alter_technicianprofile_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificatinon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('certification_id', models.CharField(max_length=50, unique=True)),
                ('institution', models.CharField(max_length=100)),
                ('date_obtained', models.DateField()),
                ('expiration_date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='technicianprofile',
            name='status',
            field=models.CharField(choices=[('Busy', 'Busy'), ('Available', 'Available'), ('Unavailable', 'Unavailable')], default='Avaiable', max_length=27),
        ),
        migrations.AddField(
            model_name='technicianprofile',
            name='certifications',
            field=models.ManyToManyField(blank=True, to='technicians.certificatinon'),
        ),
    ]
