# Generated by Django 6.0.2 on 2026-02-25 21:39

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('technicians', '0020_certificatinon_alter_technicianprofile_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='technicianprofile',
            name='certifications',
        ),
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('certification_id', models.CharField(max_length=50, unique=True)),
                ('institution', models.CharField(max_length=100)),
                ('date_obtained', models.DateField()),
                ('expiration_date', models.DateField(blank=True, null=True)),
                ('technician', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certifications', to='technicians.technicianprofile')),
            ],
        ),
        migrations.DeleteModel(
            name='Certificatinon',
        ),
    ]
