# Generated by Django 6.0.2 on 2026-02-25 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('technicians', '0021_remove_technicianprofile_certifications_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='technicianprofile',
            name='status',
            field=models.CharField(choices=[('Available', 'Available'), ('Busy', 'Busy'), ('Unavailable', 'Unavailable')], default='Avaiable', max_length=27),
        ),
    ]
