# Generated by Django 6.0.2 on 2026-02-25 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('technicians', '0022_alter_technicianprofile_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='technicianprofile',
            name='status',
            field=models.CharField(choices=[('Available', 'Available'), ('Unavailable', 'Unavailable'), ('Busy', 'Busy')], default='Avaiable', max_length=27),
        ),
    ]
