# Generated by Django 4.2 on 2026-02-26 14:00

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DiagnosticReport",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "diagnostics_id",
                    models.CharField(
                        blank=True, max_length=190, null=True, unique=True
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("severe", "Severe"),
                        ],
                        default="low",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("in_progress", "In Progress"),
                            ("resolved", "Resolved"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "specialization",
                    models.CharField(
                        choices=[
                            ("engine", "Engine Technician"),
                            ("electrical", "Electrical Technician"),
                        ],
                        default="engine",
                        max_length=50,
                    ),
                ),
                (
                    "expertise_requirement",
                    models.CharField(
                        choices=[
                            ("junior", "Junior"),
                            ("mid", "Mid"),
                            ("senior", "Senior"),
                        ],
                        default="junior",
                        max_length=50,
                    ),
                ),
                ("fault_code", models.CharField(blank=True, max_length=100, null=True)),
                ("ai_summary", models.TextField(blank=True, null=True)),
                ("probable_cause", models.TextField(blank=True, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("recommended_actions", models.TextField(blank=True, null=True)),
                ("confidence_score", models.FloatField(blank=True, null=True)),
                ("identified_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("requires_follow_up", models.BooleanField(default=False)),
                ("repeat_issue", models.BooleanField(default=False)),
                (
                    "diagnostic_duration_minutes",
                    models.IntegerField(blank=True, null=True),
                ),
                (
                    "performed_by",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
            ],
            options={
                "verbose_name": "Diagnostic Report",
                "verbose_name_plural": "Diagnostic Reports",
                "ordering": ["-created_at"],
            },
        ),
    ]
