# Generated by Django 6.0.2 on 2026-02-26 20:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        ('diagnostics', '0001_initial'),
        ('inventory', '0001_initial'),
        ('technicians', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagnosticreport',
            name='assigned_technician',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='diagnostic_reports', to='technicians.technicianprofile'),
        ),
        migrations.AddField(
            model_name='diagnosticreport',
            name='component',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='diagnostic_reports', to='inventory.component'),
        ),
        migrations.AddField(
            model_name='diagnosticreport',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='diagnostic_reports', to='customers.customerprofile'),
        ),
        migrations.AddField(
            model_name='diagnosticreport',
            name='parts',
            field=models.ManyToManyField(blank=True, related_name='diagnostic_reports', to='inventory.part'),
        ),
    ]
