# Generated by Django 4.2 on 2026-02-27 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("diagnostics", "0001_initial"),
        ("inventory", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="technicianreport",
            name="parts_used",
            field=models.ManyToManyField(blank=True, to="inventory.part"),
        ),
    ]
