# Generated by Django 4.2 on 2026-02-22 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("diagnostics", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="diagnosticreport",
            name="expertise_requirement",
            field=models.CharField(
                choices=[("Junior", "Junior"), ("Mid", "Mid"), ("Senior", "Senior")],
                default="Junior",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="diagnosticreport",
            name="specialization",
            field=models.CharField(
                choices=[
                    ("Engine", "Engine_Technician"),
                    ("Electrical", "Electrical_Technician"),
                ],
                default="Engine",
                max_length=50,
            ),
        ),
    ]
