# Generated by Django 4.2 on 2026-02-22 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("diagnostics", "0002_diagnosticreport_expertise_requirement_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="diagnosticreport",
            name="identified_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
