# Generated by Django 4.2 on 2026-02-26 14:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("diagnostics", "0002_initial"),
        ("tickets", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="diagnosticreport",
            name="ticket_id",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="diagnostic_reports",
                to="tickets.ticket",
            ),
        ),
    ]
