# Generated by Django 4.2 on 2026-02-23 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("diagnostics", "0003_diagnosticreport_identified_at"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="diagnosticreport",
            name="ticket",
        ),
    ]
