# Generated by Django 6.0.2 on 2026-02-26 21:51

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostics', '0003_initial'),
        ('inventory', '0001_initial'),
        ('technicians', '0002_initial'),
        ('tickets', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TechnicianReport',
            fields=[
                ('findings', models.TextField()),
                ('actions_taken', models.TextField()),
                ('report_id', models.CharField(blank=True, max_length=190, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('parts_used', models.ManyToManyField(blank=True, to='inventory.part')),
                ('technician', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='technicians.technicianprofile')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='technician_reports', to='tickets.ticket')),
            ],
            options={
                'verbose_name': 'Technician Report',
                'verbose_name_plural': 'Technician Reports',
                'ordering': ['-created_at'],
            },
        ),
    ]
