# Generated by Django 4.2 on 2026-02-27 06:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("customers", "0001_initial"),
        ("diagnostics", "0003_initial"),
        ("tickets", "0001_initial"),
        ("inventory", "0001_initial"),
        ("technicians", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="technicianreport",
            name="ticket",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="technician_reports",
                to="tickets.ticket",
            ),
        ),
        migrations.AddField(
            model_name="diagnosticreport",
            name="assigned_technician",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="diagnostic_reports",
                to="technicians.technicianprofile",
            ),
        ),
        migrations.AddField(
            model_name="diagnosticreport",
            name="component",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="diagnostic_reports",
                to="inventory.component",
            ),
        ),
        migrations.AddField(
            model_name="diagnosticreport",
            name="customer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="diagnostic_reports",
                to="customers.customerprofile",
            ),
        ),
        migrations.AddField(
            model_name="diagnosticreport",
            name="parts",
            field=models.ManyToManyField(
                blank=True, related_name="diagnostic_reports", to="inventory.part"
            ),
        ),
        migrations.AddField(
            model_name="diagnosticreport",
            name="ticket_id",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="diagnostic_reports",
                to="tickets.ticket",
            ),
        ),
    ]
