# Generated by Django 6.0.2 on 2026-02-26 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostics', '0004_technicianreport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diagnosticreport',
            name='severity',
            field=models.CharField(choices=[(1, 'Low'), (2, 'Medium'), (3, 'High'), (4, 'Severe')], default=2, max_length=20),
        ),
    ]
