# Generated by Django 4.2 on 2026-02-23 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("diagnostics", "0004_remove_diagnosticreport_ticket"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="diagnosticreport",
            options={
                "verbose_name": "Diagnostic Report",
                "verbose_name_plural": "Diagnostic Reports",
            },
        ),
    ]
