# Generated by Django 4.2 on 2026-02-23 16:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("inventory", "0010_alter_component_group"),
        ("diagnostics", "0005_alter_diagnosticreport_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="diagnosticreport",
            name="component",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="diagnostic_reports",
                to="inventory.component",
            ),
        ),
        migrations.AddField(
            model_name="diagnosticreport",
            name="customer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="diagnostic_reports",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="diagnosticreport",
            name="part",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name="diagnostic_reports",
                to="inventory.part",
            ),
        ),
    ]
