# Generated by Django 6.0.2 on 2026-03-06 14:39

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0002_initial"),
        ("diagnostics", "0005_alter_technicianreport_findings"),
        ("inventory", "0004_rename_statin_tool_station"),
        ("tickets", "0008_merge_20260306_1358"),
        ("users", "0013_alter_adminuserprofile_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="StaffReport",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "diagnostics_id",
                    models.CharField(
                        blank=True, max_length=190, null=True, unique=True
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "severity",
                    models.IntegerField(
                        choices=[(1, "Low"), (2, "Medium"), (3, "High"), (4, "Severe")],
                        default=2,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("in_progress", "In Progress"),
                            ("resolved", "Resolved"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "specialization",
                    models.CharField(
                        choices=[
                            ("engine", "Engine Technician"),
                            ("electrical", "Electrical Technician"),
                        ],
                        default="engine",
                        max_length=50,
                    ),
                ),
                (
                    "expertise_requirement",
                    models.CharField(
                        choices=[
                            ("junior", "Junior"),
                            ("mid", "Mid"),
                            ("senior", "Senior"),
                        ],
                        default="junior",
                        max_length=50,
                    ),
                ),
                ("fault_code", models.CharField(blank=True, max_length=100, null=True)),
                ("probable_cause", models.TextField(blank=True, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("requires_follow_up", models.BooleanField(default=False)),
                ("repeat_issue", models.BooleanField(default=False)),
                (
                    "diagnostic_duration_minutes",
                    models.IntegerField(blank=True, null=True),
                ),
                (
                    "performed_by",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "component",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="staff_reports",
                        to="inventory.component",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="technician_reports_created",
                        to="users.profile",
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="staff_reports",
                        to="customers.customerprofile",
                    ),
                ),
                (
                    "parts",
                    models.ManyToManyField(
                        blank=True, related_name="staff_reports", to="inventory.part"
                    ),
                ),
                (
                    "ticket_id",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="staff_reports",
                        to="tickets.ticket",
                    ),
                ),
            ],
            options={
                "verbose_name": "Diagnostic Report",
                "verbose_name_plural": "Diagnostic Reports",
                "ordering": ["-created_at"],
            },
        ),
        migrations.DeleteModel(
            name="TechnicianReport",
        ),
    ]
