# Generated by Django 4.2 on 2026-02-23 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0010_alter_component_group"),
        (
            "diagnostics",
            "0006_diagnosticreport_component_diagnosticreport_customer_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="diagnosticreport",
            name="part",
            field=models.ManyToManyField(
                related_name="diagnostic_reports", to="inventory.part"
            ),
        ),
    ]
