# Generated by Django 4.2 on 2026-02-23 17:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0004_remove_customerprofile_customer_info"),
        ("diagnostics", "0007_alter_diagnosticreport_part"),
    ]

    operations = [
        migrations.AlterField(
            model_name="diagnosticreport",
            name="customer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="diagnostic_reports",
                to="customers.customerprofile",
            ),
        ),
    ]
