# Generated by Django 4.2 on 2026-02-23 17:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("diagnostics", "0008_alter_diagnosticreport_customer"),
    ]

    operations = [
        migrations.AlterField(
            model_name="diagnosticreport",
            name="customer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="diagnostic_reports",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
