# Generated by Django 4.2 on 2026-02-23 19:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("technicians", "0018_alter_technicianprofile_status"),
        ("diagnostics", "0010_alter_diagnosticreport_customer"),
    ]

    operations = [
        migrations.AddField(
            model_name="diagnosticreport",
            name="assigned_technician",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="technicians.technicianprofile",
            ),
        ),
        migrations.AddField(
            model_name="diagnosticreport",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="diagnosticreport",
            name="diagnostics_id",
            field=models.CharField(blank=True, max_length=190, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="diagnosticreport",
            name="fault_code",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="diagnosticreport",
            name="performed_by",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="diagnosticreport",
            name="resolved_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="diagnosticreport",
            name="severity",
            field=models.CharField(
                choices=[
                    ("Low", "Low"),
                    ("Medium", "Medium"),
                    ("High", "High"),
                    ("Critical", "Critical"),
                ],
                default="Low",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="diagnosticreport",
            name="status",
            field=models.CharField(
                choices=[
                    ("Pending", "Pending"),
                    ("In Progress", "In Progress"),
                    ("Resolved", "Resolved"),
                    ("Failed", "Failed"),
                ],
                default="Pending",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="diagnosticreport",
            name="title",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
