# Generated by Django 6.0.2 on 2026-02-25 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostics', '0011_diagnosticreport_assigned_technician_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diagnosticreport',
            name='severity',
            field=models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('Critical', 'Critical')], default='Low', max_length=20),
        ),
        migrations.AlterField(
            model_name='diagnosticreport',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('In_Progress', 'In Progress'), ('Resolved', 'Resolved'), ('Failed', 'Failed')], default='Pending', max_length=20),
        ),
    ]
