# Generated by Django 4.2 on 2026-02-20 09:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0003_part_inventory_deducted"),
        ("manuals", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="manual",
            name="component",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="manuals",
                to="inventory.component",
            ),
        ),
        migrations.DeleteModel(
            name="Component",
        ),
    ]
