# Generated by Django 4.2 on 2026-02-27 06:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("inventory", "0002_initial"),
        ("users", "0001_initial"),
        ("manuals", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="manual",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="manuals_created",
                to="users.profile",
            ),
        ),
        migrations.AddField(
            model_name="manual",
            name="parts_needed",
            field=models.ManyToManyField(
                blank=True, related_name="manuals", to="inventory.part"
            ),
        ),
        migrations.AddField(
            model_name="manual",
            name="tags",
            field=models.ManyToManyField(
                blank=True, related_name="manuals", to="manuals.tag"
            ),
        ),
        migrations.AddField(
            model_name="image",
            name="manual",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="images",
                to="manuals.manual",
            ),
        ),
    ]
