# Generated by Django 4.2 on 2026-02-20 09:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0003_part_inventory_deducted"),
        ("manuals", "0003_alter_image_id_alter_manual_id_alter_tag_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="manual",
            name="parts_needed",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="manuals",
                to="inventory.part",
            ),
        ),
    ]
