# Generated by Django 4.2 on 2026-02-20 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0003_part_inventory_deducted"),
        ("manuals", "0004_manual_parts_needed"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="manual",
            name="component",
        ),
        migrations.RemoveField(
            model_name="manual",
            name="parts_needed",
        ),
        migrations.AddField(
            model_name="manual",
            name="component",
            field=models.ManyToManyField(
                blank=True, related_name="manuals", to="inventory.component"
            ),
        ),
        migrations.AddField(
            model_name="manual",
            name="parts_needed",
            field=models.ManyToManyField(
                blank=True, related_name="manuals", to="inventory.part"
            ),
        ),
    ]
