# Generated by Django 4.2 on 2026-02-20 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("manuals", "0005_remove_manual_component_remove_manual_parts_needed_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="manual",
            name="category",
            field=models.CharField(
                choices=[
                    ("engine", "ENGINE"),
                    ("generators", "GENERATORS"),
                    ("electrical", "ELECTRICAL"),
                    ("transmissions", "TRANSMISSIONS"),
                    ("other", "OTHER"),
                ],
                default="other",
                max_length=50,
            ),
        ),
    ]
