# Generated by Django 4.2 on 2026-02-20 18:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0007_profile_email"),
        ("manuals", "0006_manual_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="manual",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="manuals_created",
                to="users.profile",
            ),
        ),
    ]
