# Generated by Django 4.2 on 2026-02-28 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_alter_profile_city_alter_profile_country_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="adminuserprofile",
            name="status",
            field=models.CharField(
                choices=[
                    ("Busy", "Busy"),
                    ("Available", "Available"),
                    ("Unavailable", "Unavailable"),
                ],
                default="Available",
                max_length=50,
            ),
        ),
    ]
