# Generated by Django 4.2 on 2026-02-20 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_remove_user_email_address_alter_profile_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="preferences",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
