# Generated by Django 6.0.2 on 2026-03-03 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_adminuserprofile_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminuserprofile',
            name='status',
            field=models.CharField(choices=[('Unavailable', 'Unavailable'), ('Available', 'Available'), ('Busy', 'Busy')], default='Available', max_length=50),
        ),
    ]
