# Generated by Django 4.2 on 2026-02-20 08:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_profile_first_name_profile_last_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="username",
            field=models.CharField(
                blank=True,
                max_length=150,
                null=True,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Username may contain letters, digits and @/./+/-/_ characters.",
                        regex="^[\\w.@+-]+$",
                    )
                ],
            ),
        ),
    ]
