# Generated by Django 6.0.2 on 2026-03-06 02:04

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0008_alter_adminuserprofile_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="adminuserprofile",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="adminuserprofile",
            name="status",
            field=models.CharField(
                choices=[
                    ("Unavailable", "Unavailable"),
                    ("Busy", "Busy"),
                    ("Available", "Available"),
                ],
                default="Available",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="officestaffprofile",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
    ]
