# Generated by Django 4.2 on 2026-02-21 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0008_adminuserprofile_alter_user_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="role",
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
