# Generated by Django 4.2 on 2026-02-21 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0009_profile_role"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="first_name",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="last_name",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="role",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="username",
        ),
    ]
