# Generated by Django 6.0.2 on 2026-03-06 02:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0009_admin_office_uuid_pk"),
        ("users", "0009_alter_adminuserprofile_status"),
    ]

    operations = []
