# Generated by Django 4.2 on 2026-02-21 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0010_remove_profile_first_name_remove_profile_last_name_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="email",
        ),
    ]
