# Generated by Django 6.0.2 on 2026-03-06 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0010_merge_20260306_0222"),
    ]

    operations = [
        migrations.AlterField(
            model_name="adminuserprofile",
            name="status",
            field=models.CharField(
                choices=[
                    ("Unavailable", "Unavailable"),
                    ("Available", "Available"),
                    ("Busy", "Busy"),
                ],
                default="Available",
                max_length=50,
            ),
        ),
    ]
