# Generated by Django 4.2 on 2026-02-21 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0011_remove_profile_email"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="adminuserprofile",
            name="notes",
        ),
        migrations.AddField(
            model_name="profile",
            name="notes",
            field=models.TextField(blank=True, null=True),
        ),
    ]
