# Generated by Django 4.2 on 2026-02-22 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0014_station_name_alter_station_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="adminuserprofile",
            name="status",
            field=models.CharField(default="Available", max_length=50),
        ),
    ]
