# Generated by Django 6.0.2 on 2026-02-25 23:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_region'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='region',
            name='stations',
        ),
        migrations.AddField(
            model_name='station',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stations', to='users.region'),
        ),
    ]
