# Generated by Django 6.0.2 on 2026-03-10 06:02

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("customers", "0001_initial"),
        ("inventory", "0001_initial"),
        ("technicians", "0001_initial"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Ticket",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "ticket_id",
                    models.CharField(
                        blank=True, max_length=190, null=True, unique=True
                    ),
                ),
                (
                    "specialization",
                    models.CharField(
                        choices=[
                            ("engine", "Engine Technician"),
                            ("electrical", "Electrical Technician"),
                        ],
                        default="engine",
                        max_length=50,
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=200, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "severity",
                    models.IntegerField(
                        choices=[(1, "Low"), (2, "Medium"), (3, "High"), (4, "Severe")],
                        default=2,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("assigned", "Assigned"),
                            ("in_progress", "In Progress"),
                            ("awaiting_parts", "Awaiting Parts"),
                            ("awaiting_approval", "Awaiting Approval"),
                            ("completed", "Completed"),
                            ("closed", "Closed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=30,
                    ),
                ),
                (
                    "customer_satisfaction_rating",
                    models.FloatField(blank=True, null=True),
                ),
                (
                    "estimated_resolution_time_minutes",
                    models.IntegerField(
                        blank=True,
                        help_text="Predicted on-site repair time in minutes (time to fix the issue at the job site).",
                        null=True,
                    ),
                ),
                (
                    "predicted_commute_time_minutes",
                    models.IntegerField(
                        blank=True,
                        help_text="Predicted round-trip commute time in minutes (technician base to job site and back).",
                        null=True,
                    ),
                ),
                (
                    "actual_resolution_time_minutes",
                    models.IntegerField(blank=True, null=True),
                ),
                (
                    "predicted_resolution_summary",
                    models.TextField(blank=True, null=True),
                ),
                ("auto_assigned", models.BooleanField(default=False)),
                ("created_by", models.CharField(blank=True, max_length=150, null=True)),
                (
                    "priority",
                    models.IntegerField(
                        choices=[(1, "Low"), (2, "Medium"), (3, "High"), (4, "Urgent")],
                        default=2,
                    ),
                ),
                ("issue_description", models.TextField(blank=True, null=True)),
                ("checklist_template", models.JSONField(blank=True, default=list)),
                ("checklist_progress", models.JSONField(blank=True, default=list)),
                ("checklist_meta", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("assigned_at", models.DateTimeField(blank=True, null=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("closed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "assigned_technician",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_tickets",
                        to="technicians.technicianprofile",
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tickets",
                        to="customers.customerprofile",
                    ),
                ),
                (
                    "parts",
                    models.ManyToManyField(
                        blank=True, related_name="tickets", to="inventory.part"
                    ),
                ),
                (
                    "station",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tickets",
                        to="users.station",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TicketResolutionPattern",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("signature_hash", models.CharField(max_length=64, unique=True)),
                (
                    "specialization",
                    models.CharField(
                        choices=[
                            ("engine", "Engine Technician"),
                            ("electrical", "Electrical Technician"),
                        ],
                        default="engine",
                        max_length=50,
                    ),
                ),
                ("component_name", models.CharField(blank=True, max_length=255)),
                ("fault_code", models.CharField(blank=True, max_length=100)),
                ("issue_text", models.TextField(blank=True)),
                ("issue_tokens", models.JSONField(blank=True, default=list)),
                ("parts_signature", models.JSONField(blank=True, default=list)),
                ("checklist_template", models.JSONField(blank=True, default=list)),
                ("evidence", models.JSONField(blank=True, default=dict)),
                ("success_count", models.IntegerField(default=0)),
                ("last_used_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-success_count", "-updated_at"],
                "indexes": [
                    models.Index(
                        fields=["specialization", "success_count"],
                        name="tickets_tic_special_cb83ed_idx",
                    ),
                    models.Index(
                        fields=["updated_at"], name="tickets_tic_updated_be1664_idx"
                    ),
                ],
            },
        ),
    ]
