# Generated by Django 4.2 on 2026-02-27 06:36

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("technicians", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Ticket",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "ticket_id",
                    models.CharField(
                        blank=True, max_length=190, null=True, unique=True
                    ),
                ),
                (
                    "specialization",
                    models.CharField(
                        choices=[
                            ("engine", "Engine Technician"),
                            ("electrical", "Electrical Technician"),
                        ],
                        default="engine",
                        max_length=50,
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=200, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "severity",
                    models.IntegerField(
                        choices=[(1, "Low"), (2, "Medium"), (3, "High"), (4, "Severe")],
                        default=2,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("assigned", "Assigned"),
                            ("in_progress", "In Progress"),
                            ("awaiting_parts", "Awaiting Parts"),
                            ("awaiting_approval", "Awaiting Approval"),
                            ("completed", "Completed"),
                            ("closed", "Closed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=30,
                    ),
                ),
                (
                    "customer_satisfaction_rating",
                    models.FloatField(blank=True, null=True),
                ),
                (
                    "estimated_resolution_time_minutes",
                    models.IntegerField(blank=True, null=True),
                ),
                (
                    "actual_resolution_time_minutes",
                    models.IntegerField(blank=True, null=True),
                ),
                (
                    "predicted_resolution_summary",
                    models.TextField(blank=True, null=True),
                ),
                ("auto_assigned", models.BooleanField(default=False)),
                (
                    "priority",
                    models.IntegerField(
                        choices=[(1, "Low"), (2, "Medium"), (3, "High"), (4, "Urgent")],
                        default=2,
                    ),
                ),
                ("issue_description", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("assigned_at", models.DateTimeField(blank=True, null=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("closed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "assigned_technician",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_tickets",
                        to="technicians.technicianprofile",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
