# Generated by Django 4.2 on 2026-02-27 06:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("inventory", "0002_initial"),
        ("users", "0001_initial"),
        ("customers", "0002_initial"),
        ("tickets", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticket",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="tickets_created",
                to="users.profile",
            ),
        ),
        migrations.AddField(
            model_name="ticket",
            name="customer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tickets",
                to="customers.customerprofile",
            ),
        ),
        migrations.AddField(
            model_name="ticket",
            name="parts",
            field=models.ManyToManyField(
                blank=True, related_name="tickets", to="inventory.part"
            ),
        ),
    ]
