# Generated by Django 4.2 on 2026-03-05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tickets", "0003_alter_ticket_created_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticket",
            name="checklist_meta",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="ticket",
            name="checklist_progress",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="ticket",
            name="checklist_template",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
