# Generated by Django 4.2 on 2026-02-20 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tickets", "0003_ticket_created_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticket",
            name="priority",
            field=models.CharField(
                choices=[
                    ("low", "Low"),
                    ("medium", "Medium"),
                    ("high", "High"),
                    ("severe", "Severe"),
                ],
                default="medium",
                max_length=20,
            ),
        ),
    ]
