# Generated by Django 6.0.2 on 2026-03-06 00:51

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0004_ticket_checklists'),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketResolutionPattern',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('signature_hash', models.CharField(max_length=64, unique=True)),
                ('specialization', models.CharField(choices=[('engine', 'Engine Technician'), ('electrical', 'Electrical Technician')], default='engine', max_length=50)),
                ('component_name', models.CharField(blank=True, max_length=255)),
                ('fault_code', models.CharField(blank=True, max_length=100)),
                ('issue_text', models.TextField(blank=True)),
                ('issue_tokens', models.JSONField(blank=True, default=list)),
                ('parts_signature', models.JSONField(blank=True, default=list)),
                ('checklist_template', models.JSONField(blank=True, default=list)),
                ('evidence', models.JSONField(blank=True, default=dict)),
                ('success_count', models.IntegerField(default=0)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-success_count', '-updated_at'],
                'indexes': [models.Index(fields=['specialization', 'success_count'], name='tickets_tic_special_cb83ed_idx'), models.Index(fields=['updated_at'], name='tickets_tic_updated_be1664_idx')],
            },
        ),
    ]
