# Generated by Django 4.2 on 2026-02-23 16:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("diagnostics", "0004_remove_diagnosticreport_ticket"),
        ("tickets", "0004_ticket_priority"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticket",
            name="associated_diagnosis",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="tickets",
                to="diagnostics.diagnosticreport",
            ),
        ),
    ]
