# Generated by Django 4.2 on 2026-02-23 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tickets", "0005_ticket_associated_diagnosis"),
    ]

    operations = [
        migrations.RenameField(
            model_name="ticket",
            old_name="associated_diagnosis",
            new_name="diagnosticReport",
        ),
    ]
