# Generated by Django 6.0.2 on 2026-03-06 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tickets", "0005_add_predicted_commute_time_minutes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ticket",
            name="estimated_resolution_time_minutes",
            field=models.IntegerField(
                blank=True,
                help_text="Predicted on-site repair time in minutes (time to fix the issue at the job site).",
                null=True,
            ),
        ),
    ]
