# Generated by Django 4.2 on 2026-02-23 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tickets", "0006_rename_associated_diagnosis_ticket_diagnosticreport"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ticket",
            name="customer",
        ),
    ]
