# Generated by Django 6.0.2 on 2026-02-25 23:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0004_remove_customerprofile_customer_info'),
        ('tickets', '0007_remove_ticket_customer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='assigned_to',
            new_name='technician',
        ),
        migrations.AddField(
            model_name='ticket',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='customers.customerprofile'),
        ),
    ]
