# Generated by Django 6.0.2 on 2026-03-06 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tickets", "0005_ticketresolutionpattern"),
        ("tickets", "0007_ticket_station"),
    ]

    operations = []
