# Generated by Django 6.0.2 on 2026-03-06 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tickets", "0008_merge_20260306_1358"),
        ("tickets", "0008_merge_20260306_1613"),
    ]

    operations = []
