# Generated by Django 6.0.2 on 2026-02-19 17:47

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Component',
            fields=[
                ('group', models.CharField(choices=[('engine', 'ENGINE'), ('generators', 'GENERATORS'), ('electrical', 'ELECTRICAL'), ('transmissions', 'TRANSMISSIONS')], max_length=50)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Part',
            fields=[
                ('part_number', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('quantity_available', models.IntegerField(default=0)),
                ('reorder_threshold', models.IntegerField(default=5)),
                ('supplier', models.CharField(max_length=255)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parts', to='inventory.component')),
            ],
        ),
        migrations.CreateModel(
            name='InventoryTransaction',
            fields=[
                ('transaction_type', models.CharField(choices=[('addition', 'Addition'), ('removal', 'Removal')], max_length=20)),
                ('quantity', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.part')),
            ],
        ),
    ]
