# Generated by Django 4.2 on 2026-02-27 06:36

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Component",
            fields=[
                (
                    "group",
                    models.CharField(
                        choices=[
                            ("Engine", "ENGINE"),
                            ("Generators", "GENERATORS"),
                            ("Electrical", "ELECTRICAL"),
                            ("Transmissions", "TRANSMISSIONS"),
                        ],
                        default="engine",
                        max_length=50,
                    ),
                ),
                (
                    "component_number",
                    models.CharField(
                        blank=True, max_length=100, null=True, unique=True
                    ),
                ),
                ("quantity_available", models.IntegerField(default=1)),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="InventoryTransaction",
            fields=[
                (
                    "transaction_type",
                    models.CharField(
                        choices=[("addition", "Addition"), ("removal", "Removal")],
                        max_length=20,
                    ),
                ),
                ("quantity", models.IntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Part",
            fields=[
                ("part_number", models.CharField(max_length=100, unique=True)),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                ("quantity_available", models.IntegerField(default=0)),
                ("reorder_threshold", models.IntegerField(default=5)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("engine", "ENGINE"),
                            ("generators", "GENERATORS"),
                            ("electrical", "ELECTRICAL"),
                            ("transmissions", "TRANSMISSIONS"),
                            ("other", "OTHER"),
                        ],
                        default="other",
                        max_length=50,
                    ),
                ),
                ("weight_kg", models.IntegerField(blank=True, null=True)),
                (
                    "cost_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "resale_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("in_stock", "In Stock"),
                            ("out_of_stock", "Out of Stock"),
                            ("discontinued", "Discontinued"),
                            ("backordered", "Backordered"),
                        ],
                        default="in_stock",
                        max_length=20,
                    ),
                ),
                ("supplier", models.CharField(max_length=255)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("inventory_deducted", models.BooleanField(default=False)),
                ("last_ordered_at", models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Tool",
            fields=[
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                ("quantity_available", models.IntegerField(default=1)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
