# Generated by Django 6.0.2 on 2026-02-19 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='part',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
