# Generated by Django 4.2 on 2026-02-27 06:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("users", "0001_initial"),
        ("inventory", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="tool",
            name="statin",
            field=models.ManyToManyField(related_name="tools", to="users.station"),
        ),
        migrations.AddField(
            model_name="part",
            name="components",
            field=models.ManyToManyField(
                related_name="parts", to="inventory.component"
            ),
        ),
        migrations.AddField(
            model_name="inventorytransaction",
            name="part",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="inventory.part"
            ),
        ),
    ]
