# Generated by Django 4.2 on 2026-02-27 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="component",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="component_images/"
            ),
        ),
        migrations.AddField(
            model_name="part",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="part_images/"),
        ),
    ]
