# Generated by Django 6.0.2 on 2026-02-20 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_part_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='part',
            name='inventory_deducted',
            field=models.BooleanField(default=False),
        ),
    ]
