# Generated by Django 6.0.2 on 2026-03-06 01:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0003_component_image_part_image"),
    ]

    operations = [
        migrations.RenameField(
            model_name="tool",
            old_name="statin",
            new_name="station",
        ),
    ]
