# Generated by Django 4.2 on 2026-02-20 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0003_part_inventory_deducted"),
    ]

    operations = [
        migrations.AddField(
            model_name="part",
            name="category",
            field=models.CharField(
                choices=[
                    ("engine", "ENGINE"),
                    ("generators", "GENERATORS"),
                    ("electrical", "ELECTRICAL"),
                    ("transmissions", "TRANSMISSIONS"),
                    ("other", "OTHER"),
                ],
                default="other",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="part",
            name="cost_price",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="part",
            name="resale_price",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="part",
            name="status",
            field=models.CharField(
                choices=[
                    ("in_stock", "In Stock"),
                    ("out_of_stock", "Out of Stock"),
                    ("discontinued", "Discontinued"),
                    ("backordered", "Backordered"),
                ],
                default="in_stock",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="part",
            name="weight",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
