# Generated by Django 4.2 on 2026-02-20 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0004_part_category_part_cost_price_part_resale_price_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="part",
            old_name="weight",
            new_name="weight_kg",
        ),
    ]
