# Generated by Django 4.2 on 2026-02-20 18:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0005_rename_weight_part_weight_kg"),
    ]

    operations = [
        migrations.AlterField(
            model_name="part",
            name="component",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="parts",
                to="inventory.component",
            ),
        ),
    ]
