# Generated by Django 4.2 on 2026-02-20 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0006_alter_part_component"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="part",
            name="component",
        ),
        migrations.AddField(
            model_name="part",
            name="components",
            field=models.ManyToManyField(
                related_name="parts", to="inventory.component"
            ),
        ),
    ]
