# Generated by Django 4.2 on 2026-02-22 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0007_remove_part_component_part_components"),
    ]

    operations = [
        migrations.AddField(
            model_name="component",
            name="component_number",
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="component",
            name="quantity_available",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="component",
            name="group",
            field=models.CharField(
                choices=[
                    ("engine", "ENGINE"),
                    ("generators", "GENERATORS"),
                    ("electrical", "ELECTRICAL"),
                    ("transmissions", "TRANSMISSIONS"),
                ],
                default="engine",
                max_length=50,
            ),
        ),
    ]
