# Generated by Django 4.2 on 2026-02-22 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0008_component_component_number_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="component",
            name="quantity_available",
            field=models.IntegerField(default=1),
        ),
    ]
