# Generated by Django 4.2 on 2026-02-23 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0009_alter_component_quantity_available"),
    ]

    operations = [
        migrations.AlterField(
            model_name="component",
            name="group",
            field=models.CharField(
                choices=[
                    ("Engine", "ENGINE"),
                    ("Generators", "GENERATORS"),
                    ("Electrical", "ELECTRICAL"),
                    ("Transmissions", "TRANSMISSIONS"),
                ],
                default="engine",
                max_length=50,
            ),
        ),
    ]
