# Generated by Django 6.0.2 on 2026-02-26 20:40

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('asset_type', models.CharField(choices=[('engine', 'Engine'), ('generator', 'Generator'), ('other', 'Other'), ('vehicle', 'Vehicle')], max_length=50)),
                ('product_id', models.CharField(editable=False, max_length=10, unique=True)),
                ('serial_number', models.CharField(max_length=100)),
                ('model_number', models.CharField(max_length=100)),
                ('id', models.AutoField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
            ],
        ),
    ]
