# Generated by Django 6.0.2 on 2026-03-10 06:02

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("customers", "0001_initial"),
        ("inventory", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Asset",
            fields=[
                (
                    "asset_type",
                    models.CharField(
                        choices=[
                            ("engine", "Engine"),
                            ("generator", "Generator"),
                            ("other", "Other"),
                            ("vehicle", "Vehicle"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "product_id",
                    models.CharField(editable=False, max_length=10, unique=True),
                ),
                ("serial_number", models.CharField(max_length=100)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "component",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assets",
                        to="inventory.component",
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="customers.customerprofile",
                    ),
                ),
            ],
        ),
    ]
