# Generated by Django 6.0.2 on 2026-03-06 17:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assets", "0002_initial"),
        ("inventory", "0004_rename_statin_tool_station"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="asset",
            name="model_number",
        ),
        migrations.AddField(
            model_name="asset",
            name="component",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assets",
                to="inventory.component",
            ),
        ),
    ]
