# Generated by Django 6.0.2 on 2026-03-06 18:06

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assets", "0003_remove_asset_model_number_asset_component"),
    ]

    operations = [
        migrations.AlterField(
            model_name="asset",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
    ]
