# Generated by Django 4.2 on 2026-02-27 06:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("logs", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="activitylog",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="activity_logs",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="activitylog",
            index=models.Index(fields=["user"], name="logs_activi_user_id_25bf84_idx"),
        ),
        migrations.AddIndex(
            model_name="activitylog",
            index=models.Index(
                fields=["event_type"], name="logs_activi_event_t_37fd43_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="activitylog",
            index=models.Index(
                fields=["severity"], name="logs_activi_severit_855758_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="activitylog",
            index=models.Index(
                fields=["created_at"], name="logs_activi_created_fcb94f_idx"
            ),
        ),
    ]
