# Generated by Django 6.0.2 on 2026-03-06 03:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("logs", "0002_initial"),
        ("users", "0012_alter_adminuserprofile_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="activitylog",
            name="station",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="logs",
                to="users.station",
            ),
        ),
    ]
