# Generated by Django 6.0.2 on 2026-02-28 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='knowledgechunk',
            name='embedding',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
