# Generated by Codex on 2026-03-01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai", "0002_knowledgechunk_embedding"),
    ]

    operations = [
        migrations.CreateModel(
            name="AgentPromptConfig",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("slug", models.CharField(default="current", max_length=64, unique=True)),
                ("system_prompt", models.TextField()),
                ("domain_guardrail_prompt", models.TextField()),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-updated_at"],
            },
        ),
    ]
