# Generated by Django 6.0.2 on 2026-03-01 04:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0003_agentpromptconfig'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='mcpadapter',
            name='auth_type',
            field=models.CharField(choices=[('none', 'None'), ('bearer', 'Bearer'), ('api_key', 'API Key'), ('oauth2', 'OAuth 2.0'), ('custom', 'Custom')], default='none', max_length=32),
        ),
        migrations.CreateModel(
            name='AgentActionProposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('create_ticket', 'Create Ticket'), ('assign_employee', 'Assign Employee'), ('order_part', 'Order Part')], max_length=64)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('executed', 'Executed'), ('failed', 'Failed')], default='pending', max_length=32)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('result', models.JSONField(blank=True, default=dict)),
                ('error', models.TextField(blank=True)),
                ('source_query', models.TextField(blank=True)),
                ('source_context', models.JSONField(blank=True, default=dict)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('executed_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_agent_action_proposals', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_agent_action_proposals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AgentExecutionTrace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(default='execution', max_length=64)),
                ('tool_name', models.CharField(blank=True, max_length=255)),
                ('ok', models.BooleanField(default=False)),
                ('status_code', models.IntegerField(default=0)),
                ('duration_ms', models.IntegerField(default=0)),
                ('request_payload', models.JSONField(blank=True, default=dict)),
                ('response_payload', models.JSONField(blank=True, default=dict)),
                ('error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('adapter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='execution_traces', to='ai.mcpadapter')),
                ('proposal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='traces', to='ai.agentactionproposal')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='agentactionproposal',
            index=models.Index(fields=['status', 'action_type'], name='ai_agentact_status_46bf73_idx'),
        ),
        migrations.AddIndex(
            model_name='agentactionproposal',
            index=models.Index(fields=['created_at'], name='ai_agentact_created_8b223e_idx'),
        ),
        migrations.AddIndex(
            model_name='agentexecutiontrace',
            index=models.Index(fields=['stage', 'created_at'], name='ai_agentexe_stage_58493d_idx'),
        ),
    ]
