# Generated by Django 6.0.2 on 2026-03-06 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai", "0004_alter_mcpadapter_auth_type_agentactionproposal_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="agentactionproposal",
            name="action_type",
            field=models.CharField(
                choices=[
                    ("create_ticket", "Create Ticket"),
                    ("update_ticket", "Update Ticket"),
                    ("assign_employee", "Assign Employee"),
                    ("order_part", "Order Part"),
                ],
                max_length=64,
            ),
        ),
    ]
