# Generated by Django 6.0.2 on 2026-03-06 14:58

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0004_alter_mcpadapter_auth_type_agentactionproposal_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FelixChatThread',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, default='', max_length=255)),
                ('shared_token', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('shared_at', models.DateTimeField(blank=True, null=True)),
                ('last_message_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='felix_chat_threads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-last_message_at', '-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='FelixChatMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant'), ('system', 'System')], default='user', max_length=16)),
                ('content', models.TextField(blank=True, default='')),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='ai.felixchatthread')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='felixchatthread',
            index=models.Index(fields=['owner', '-last_message_at'], name='ai_felixcha_owner_i_8a8700_idx'),
        ),
        migrations.AddIndex(
            model_name='felixchatthread',
            index=models.Index(fields=['shared_token'], name='ai_felixcha_shared__589b56_idx'),
        ),
        migrations.AddIndex(
            model_name='felixchatmessage',
            index=models.Index(fields=['thread', 'created_at'], name='ai_felixcha_thread__24afaf_idx'),
        ),
        migrations.AddIndex(
            model_name='felixchatmessage',
            index=models.Index(fields=['role'], name='ai_felixcha_role_1bbe9b_idx'),
        ),
    ]
