# Generated by Django 6.0.2 on 2026-03-06 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0005_add_update_ticket_action'),
        ('ai', '0005_felixchatthread_felixchatmessage_and_more'),
    ]

    operations = [
    ]
