"""
Django settings for breakthru project.

Generated by 'django-admin startproject' using Django 5.1.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""
import os
from datetime import timedelta
from pathlib import Path
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.

BASE_DIR = Path(__file__).resolve().parent.parent.parent
PROJECT_DIR = BASE_DIR.parent
WORKSPACE_DIR = PROJECT_DIR.parent

# load_dotenv(PROJECT_DIR / ".env")     # cummins code/.env
# load_dotenv(WORKSPACE_DIR / ".env")   # Downloads/.env
load_dotenv(BASE_DIR / ".env")


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv("SECRET_KEY", "django-insecure-#)b1e^*a$(zc55^(fhaqqa%e9(xcy7zcrg(97hn+^f!o@bb%82")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv("DEBUG", "False").lower() in {"1", "true", "yes"}

allowed_hosts_env = os.getenv("ALLOWED_HOSTS", "").strip()
if allowed_hosts_env:
    ALLOWED_HOSTS = [host.strip() for host in allowed_hosts_env.split(",") if host.strip()]
else:
    # Development-friendly default so local UI hosts do not break login with DisallowedHost.
    ALLOWED_HOSTS = ["*"] if DEBUG else ["localhost", "127.0.0.1", "breakthru-dashboard.vercel.app"]


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",

    # installed apps
    'apps.agents.apps.AgentsConfig',
    'apps.assets.apps.AssetsConfig',
    'apps.customers.apps.CustomersConfig',
    'apps.diagnostics.apps.DiagnosticsConfig',
    'apps.inventory.apps.InventoryConfig',
    'apps.logs.apps.LogsConfig',
    'apps.manuals.apps.ManualsConfig',
    'apps.orders.apps.OrdersConfig',
    'apps.routing.apps.RoutingConfig',
    'apps.technicians.apps.TechniciansConfig',
    'apps.tickets.apps.TicketsConfig',
    'apps.users.apps.UsersConfig',
    'apps.notifications.apps.NotificationsConfig',
    'apps.staffs.apps.StaffsConfig',
    'apps.schedules.apps.SchedulesConfig',
    # 'apps.regions.apps.RegionsConfig',
    'apps.playbooks.apps.PlaybooksConfig',
    'apps.ai.apps.AiConfig',

    'rest_framework',
    'channels',
    'corsheaders',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "breakthru.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "breakthru.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

# Use DATABASE_URL if provided (for Supabase/Render), otherwise use individual settingspython 
import dj_database_url

# For Supabase with connection pooling, use DIRECT_URL for migrations
database_url = os.getenv("DIRECT_URL") or os.getenv("DATABASE_URL")
if database_url:
    DATABASES = {
        "default": dj_database_url.config(
            default=database_url,
            conn_max_age=600,
            conn_health_checks=True,
            ssl_require=True,  # Supabase requires SSL
        )
    }
# else:
#     db_engine = os.getenv("DB_ENGINE", "django.db.backends.sqlite3")
#     is_sqlite = "sqlite3" in db_engine
    
#     DATABASES = {
#         "default": {
#             "ENGINE": db_engine,
#             "NAME": BASE_DIR / "db.sqlite3" if is_sqlite else os.getenv("DB_NAME", "postgres"),
#             "USER": os.getenv("DB_USER", ""),
#             "PASSWORD": os.getenv("DB_PASSWORD", ""),
#             "HOST": os.getenv("DB_HOST", "localhost"),
#             "PORT": os.getenv("DB_PORT", "5432"),
#             "OPTIONS": {
#                 "sslmode": "require",  # For Supabase
#             } if not is_sqlite else {},
#         }
#     }


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "apps.users.authentication.OptionalJWTAuthentication",
        "rest_framework.authentication.SessionAuthentication",
    ),
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.AllowAny",
    ],
    "DEFAULT_RENDERER_CLASSES": (
        "rest_framework.renderers.JSONRenderer",
    ),
    "UNAUTHENTICATED_USER": None,
}

# JWT: longer TTL so users aren’t logged out quickly (default was 5 min access)
SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(hours=24),   # 1 day
    "REFRESH_TOKEN_LIFETIME": timedelta(days=7),    # 7 days
}

CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels_redis.core.RedisChannelLayer",
        "CONFIG": {
            "hosts": [(os.getenv("REDIS_HOST", "localhost"), int(os.getenv("REDIS_PORT", 6379)))],
        },
    },
}

if DEBUG and os.getenv("CORS_ALLOW_ALL_ORIGINS", "true").lower() in {"1", "true", "yes"}:
    CORS_ALLOW_ALL_ORIGINS = True
else:
    cors_origins_env = os.getenv("CORS_ALLOWED_ORIGINS", "")
    if cors_origins_env:
        CORS_ALLOWED_ORIGINS = [origin.strip() for origin in cors_origins_env.split(",") if origin.strip()]
    else:
        CORS_ALLOWED_ORIGINS = [
            "http://localhost:8080",
            "http://127.0.0.1:8080",
            "http://localhost:8081",
            "http://127.0.0.1:8081",
            "http://localhost:5173",
            "http://127.0.0.1:5173",
            "http://localhost:3000",
            "http://127.0.0.1:3000",
            "https://breakthru-dashboard.vercel.app",
        ]
# Let frontend send Authorization header and cookies
CORS_ALLOW_CREDENTIALS = True


AUTH_USER_MODEL = "users.User"

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = "static/"

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# Production Security Settings
if not DEBUG:
    SECURE_SSL_REDIRECT = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_BROWSER_XSS_FILTER = True
    SECURE_CONTENT_SECURITY_POLICY = {
        "default-src": ("'self'",),
    }
