# Generated by Django 6.0.2 on 2026-02-26 20:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('schedules', '0001_initial'),
        ('technicians', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='technician',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='technicians.technicianprofile'),
        ),
    ]
