# Generated by Django 6.0.2

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schedules", "0003_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="schedule",
            name="ended_at",
            field=models.DateTimeField(blank=True, help_text="When this schedule was stopped (technician moved to another ticket).", null=True),
        ),
    ]
