# Generated by Django 6.0.2 on 2026-03-10 06:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("message", models.TextField()),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("order_approved", "Order Approved"),
                            ("order_rejected", "Order Rejected"),
                            ("order_created", "Order Created"),
                            ("ticket_created", "Ticket Created"),
                            ("ticket_assigned", "Ticket Assigned"),
                            ("ticket_status_changed", "Ticket Status Changed"),
                            ("parts_ready_for_pickup", "Parts Ready For Pickup"),
                            ("asset_updated", "Asset Updated"),
                        ],
                        max_length=50,
                    ),
                ),
                ("data", models.JSONField(blank=True, default=dict)),
                ("is_read", models.BooleanField(default=False)),
                ("read_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "recipient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
