# Generated by Django 6.0.2 on 2026-03-05 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="data",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="notification",
            name="read_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="notification",
            name="type",
            field=models.CharField(
                choices=[
                    ("order_approved", "Order Approved"),
                    ("order_rejected", "Order Rejected"),
                    ("order_created", "Order Created"),
                    ("ticket_created", "Ticket Created"),
                    ("ticket_assigned", "Ticket Assigned"),
                    ("ticket_status_changed", "Ticket Status Changed"),
                    ("parts_ready_for_pickup", "Parts Ready For Pickup"),
                    ("asset_updated", "Asset Updated"),
                ],
                max_length=50,
            ),
        ),
    ]
